### ISSUE TITLE
XCode 6.3.2 – menu item is missing after XCode relaunch

### ISSUE THREAD

**Issue by norlin** [ryanmeisters/Xcode-Plugin-Open-Sublime-Text#12]
Not sure if it's related to #5 issue, but for me the 'Open in Sublime' menu item is missing every time after XCode relaunch.
Need to re-install plugin via Alcatraz to restore it.

**Comment by ryanmeisters** [comment]
Yeah I think the problem is that the menu item is installed in the menu on `NSWindowDidBecomeKeyNotification`s. Apparently this worked reasonably well when I first made the plugin, but it doesn't seem to work so well in Xcode 6. 

My current bandaid is to switch to another window and back quickly (command + tab).

**Comment by pasta12** [comment]
@ryanmeisters Is there any reason not to do the menu item setup in `initWithBundle:`? That's where I do it in the plugin I'm working on, and I haven't seen any issues.

**Comment by KellyBennett** [comment]
@ryanmeisters The baindaid is not working for me. Switching windows seems to have no effect. The menu item stays gone until I remove and (re)install the plugin via Alcatraz. Also (possibly related?) the menu item never shows up in xcode's keybindings.

**Comment by ryanmeisters** [comment]
.. actually it doesn't seem to be working for me anymore either.. 

@pasta12 I don't quite remember, but I think it didn't work. It might have been something like the Editor menu item doesn't exist yet in `initWithBundle:`.

**Comment by pasta12** [comment]
[This tutorial](http://www.raywenderlich.com/94020/creating-an-xcode-plugin-part-1) was posted on 6-2-2015 and discusses adding a menu item that persists across multiple Xcode launches. Maybe take inspiration from that?

**Comment by pasta12** [comment]
Should be able to use the `NSApplicationDidFinishLaunchingNotification`

**Comment by ryanmeisters** [comment]
So the plugin actually stopped working due to missing DVTPlugInCompatibilityUUIDs. 

I did a tiny bit of testing. Neither `NSApplicationDidFinishLaunchingNotification` or `initWithBundle:` seem to work for adding the menu item to the Editor menu. 

I've just released 1.4.0, which adds the necessary DVTPlugInCompatibilityUUIDs and restores functionality. The menu item is still added on `NSWindowDidBecomeKeyNotification`s, which doesn't work 100%, but does alright. 

Let me know if you guys have any ideas on how to do this better.

**Comment by ryanmeisters** [comment]
Also, @KellyBennett, it won't show up in Xcode's key bindings. I haven't found any examples of how to do that, and haven't had time to go digging through decompiled source to find out. 

Currently the best option is an OS X keyboard shortcut

**Comment by KellyBennett** [comment]
@ryanmeisters  Working great now. Thanks!
